Repository Morpheus-Fatec/morpheus, pull requests merged in 2024-12, with the labels that each got.

#144 [G][Criação da Interface] Interface de gerenciamento de API. #128
  front-end/html/api.html
  front-end/html/newsFeed.html
  front-end/js/api.js
Labels: enhancement, build

#147 [H][Gerenciamento de API] Processo de Salvamento de Dados de APIs #130
  back-end/src/main/java/fatec/morpheus/DTO/ApiDTO.java
  back-end/src/main/java/fatec/morpheus/MorpheusApplication.java
  back-end/src/main/java/fatec/morpheus/controller/ApiController.java
  back-end/src/main/java/fatec/morpheus/database/ddl.sql
  back-end/src/main/java/fatec/morpheus/entity/Api.java
  back-end/src/main/java/fatec/morpheus/entity/ApiContent.java
  back-end/src/main/java/fatec/morpheus/entity/TagRelFont.java
  back-end/src/main/java/fatec/morpheus/repository/ApiContentRepository.java
  back-end/src/main/java/fatec/morpheus/repository/TagRelFontRepository.java
  back-end/src/main/java/fatec/morpheus/repository/TagRepository.java
  back-end/src/main/java/fatec/morpheus/service/ApiContentService.java
  back-end/src/main/java/fatec/morpheus/service/ApiService.java
  back-end/src/main/java/fatec/morpheus/service/CronManager.java
  back-end/src/main/java/fatec/morpheus/service/TagService.java
Labels: enhancement, build

#125 [Aprimoramento técnico] Aplicar o regionalismo ao filtro de notícias #122
  back-end/src/main/java/fatec/morpheus/service/AdaptedTagsService.java
  back-end/src/main/java/fatec/morpheus/service/ApiService.java
  back-end/src/main/java/fatec/morpheus/service/NewsService.java
  back-end/src/main/java/fatec/morpheus/service/NewsSpecification.java
Labels: enhancement, build

#149 [Aprimoramento técnico] Tutorial Interativo Filtros #148
  front-end/html/apiFeed.html
  front-end/html/newsFeed.html
  front-end/js/apiFeed.js
  front-end/js/newsFeed.js
Labels: documentation, enhancement

#152 [Aprimoramento técnico] Tutorial Interativo APIS #151
  front-end/html/api.html
  front-end/js/api.js
Labels: documentation

#154 Filtros busca dados de api
  back-end/src/main/java/fatec/morpheus/DTO/ApiEndpointDTO.java
  back-end/src/main/java/fatec/morpheus/DTO/ApiFilterRequestDTO.java
  back-end/src/main/java/fatec/morpheus/DTO/ApiFilterResponseDTO.java
  back-end/src/main/java/fatec/morpheus/controller/ApiController.java
  back-end/src/main/java/fatec/morpheus/entity/Api.java
  back-end/src/main/java/fatec/morpheus/entity/ApiResponse.java
  back-end/src/main/java/fatec/morpheus/repository/ApiContentRepository.java
  back-end/src/main/java/fatec/morpheus/repository/ApiRepository.java
  back-end/src/main/java/fatec/morpheus/service/ApiContentService.java
  back-end/src/main/java/fatec/morpheus/service/ApiService.java
  back-end/src/main/java/fatec/morpheus/service/ApiSpecification.java
  documentation/burndown/BurnDownChartSprint3.png
Labels: enhancement

#157 Documentation sprint 4
  README.md
  documentation/burndown/BurnDownChartSprint4.png
Labels: documentation

#156 [Aprimoramento Técnico] Integração dos Endpoints para APIs #155
  front-end/js/apiFeed.js
Labels: build
