Repository Morpheus-Fatec/morpheus, pull requests merged in 2024-10, with the labels that each got.

#37 Tratando excecoes source api
  .vscode/settings.json
  back-end/pom.xml
  back-end/src/main/java/fatec/morpheus/controller/NewsSourceController.java
  back-end/src/main/java/fatec/morpheus/entity/ErrorResponse.java
  back-end/src/main/java/fatec/morpheus/entity/NewsSource.java
  back-end/src/main/java/fatec/morpheus/exception/GlobalExceptionHandler.java
  back-end/src/main/java/fatec/morpheus/exception/InvalidFieldException.java
  back-end/src/main/java/fatec/morpheus/exception/NotFoundException.java
  back-end/src/main/java/fatec/morpheus/exception/UniqueConstraintViolationException.java
  back-end/src/main/java/fatec/morpheus/repository/NewsSourceRepository.java
  back-end/src/main/java/fatec/morpheus/service/NewsSourceService.java
  documentation/diagrams/morpheus-bd.png
Labels: bug

#32 Configuração da conexão do sistema com o banco de dados #4
  README.md
  back-end/src/main/java/fatec/morpheus/entity/NewsSource.java
  back-end/src/main/java/fatec/morpheus/repository/NewsSourceRepository.java
  back-end/src/main/java/fatec/morpheus/service/NewsSourceService.java
  documentation/manuals/hibernate/images/dataBaseInformations.png
  documentation/manuals/hibernate/images/database.png
  documentation/manuals/hibernate/images/manageConnections.png
  documentation/manuals/hibernate/images/properties.png
  documentation/manuals/hibernate/images/usernameAndPassword.png
  documentation/manuals/hibernate/manual-hibernate.md
  front-end/js/managerNews.js
Labels: documentation

#46 :bug: fix: correcao tabela duplicando
  back-end/src/main/java/fatec/morpheus/entity/NewsSource.java
  back-end/src/main/resources/application.properties
  front-end/html/index.html
Labels: bug

#51 [feat] Gerenciamento de sinônimos #36
  back-end/src/main/java/fatec/morpheus/controller/TextoController.java
  back-end/src/main/java/fatec/morpheus/database/ddl.sql
  back-end/src/main/java/fatec/morpheus/entity/Synonymous.java
  back-end/src/main/java/fatec/morpheus/entity/SynonymousId.java
  back-end/src/main/java/fatec/morpheus/entity/Texto.java
  back-end/src/main/java/fatec/morpheus/repository/SynonymousRepository.java
  back-end/src/main/java/fatec/morpheus/repository/TextoRepository.java
  back-end/src/main/java/fatec/morpheus/service/SynonymousService.java
  back-end/src/main/java/fatec/morpheus/service/TextoService.java
Labels: build

#53 Atualização do gráfico Burndown
  documentation/burndown/BurnDownChartSprint2.png
Labels: documentation

#60 Atualização do gráfico burndown
  documentation/burndown/BurnDownChartSprint2.png
Labels: documentation

#49 [D][Feat] Consulta notícias no banco de dados #43
  back-end/src/main/java/fatec/morpheus/controller/NewsController.java
  back-end/src/main/java/fatec/morpheus/database/ddl.sql
  back-end/src/main/java/fatec/morpheus/entity/News.java
  back-end/src/main/java/fatec/morpheus/entity/NewsAuthor.java
  back-end/src/main/java/fatec/morpheus/entity/NewsReponse.java
  back-end/src/main/java/fatec/morpheus/entity/NewsSource.java
  back-end/src/main/java/fatec/morpheus/entity/PaginatedNewsResponse.java
  back-end/src/main/java/fatec/morpheus/repository/NewsAuthorRepository.java
  back-end/src/main/java/fatec/morpheus/repository/NewsRepository.java
  back-end/src/main/java/fatec/morpheus/service/NewsService.java
Labels: enhancement, build

#61 [D] [Criação da Interface] Interface de gerênciamento do cronograma de coleta de dados. #55
  front-end/css/base.css
  front-end/html/index.html
  front-end/js/index.js
Labels: enhancement, build

#58 [D] [Web Scrapping] Agendamento de Coletas de Dados #44
  back-end/pom.xml
  back-end/src/main/java/fatec/morpheus/MorpheusApplication.java
  back-end/src/main/java/fatec/morpheus/config/CronConfig.java
  back-end/src/main/java/fatec/morpheus/controller/CronController.java
  back-end/src/main/java/fatec/morpheus/entity/CronProperties.java
  back-end/src/main/java/fatec/morpheus/service/CronManager.java
  back-end/src/main/resources/application.properties
Labels: enhancement, build

#57 [D] [Web Scrapping] Mapeando tags html de uma fonte de exemplo
  back-end/pom.xml
  back-end/src/main/java/fatec/morpheus/DTO/MapSourceDTO.java
  back-end/src/main/java/fatec/morpheus/DTO/MappingDTO.java
  back-end/src/main/java/fatec/morpheus/DTO/NewsSourceDTO.java
  back-end/src/main/java/fatec/morpheus/controller/NewsSourceController.java
  back-end/src/main/java/fatec/morpheus/database/ddl.sql
  back-end/src/main/java/fatec/morpheus/entity/ErrorResponse.java
  back-end/src/main/java/fatec/morpheus/entity/MapSource.java
  back-end/src/main/java/fatec/morpheus/entity/NewsSource.java
  back-end/src/main/java/fatec/morpheus/entity/Synonymous.java
  back-end/src/main/java/fatec/morpheus/entity/Tag.java
  back-end/src/main/java/fatec/morpheus/exception/GlobalExceptionHandler.java
  back-end/src/main/java/fatec/morpheus/exception/InvalidFieldException.java
  back-end/src/main/java/fatec/morpheus/exception/NotFoundException.java
  back-end/src/main/java/fatec/morpheus/exception/UniqueConstraintViolationException.java
  back-end/src/main/java/fatec/morpheus/repository/MapSourceRepository.java
  back-end/src/main/java/fatec/morpheus/repository/SynonymousRepository.java
  back-end/src/main/java/fatec/morpheus/service/MapSourceService.java
  back-end/src/main/java/fatec/morpheus/service/NewsSourceService.java
  back-end/src/main/resources/application.properties
Labels: enhancement

#64 [D] [Criação da Interface] Interface de gerenciamento de palavra sinônimos #35
  front-end/html/index.html
  front-end/js/index.js
Labels: enhancement, build

#63 [C] [Criação da Interface] Interface de gerenciamento de notícias #54
  front-end/html/newsFeed.html
  front-end/js/newsFeed.js
Labels: enhancement, build

#69 [D] [Web Scrapping] Cadastro de Notícias no Banco de Dados
  back-end/src/main/java/fatec/morpheus/database/ddl.sql
  back-end/src/main/java/fatec/morpheus/entity/News.java
  back-end/src/main/java/fatec/morpheus/entity/NewsReponse.java
  back-end/src/main/java/fatec/morpheus/service/NewsService.java
Labels: enhancement, build

#68 [C] [Refactor] Geração de tags virtuais a partir do código da fonte de notícias. #66
  back-end/src/main/java/fatec/morpheus/service/AdaptedTagsService.java
Labels: enhancement, build

#73 [FIX]Consulta notícias no banco de dados 72#
  back-end/src/main/java/fatec/morpheus/controller/NewsController.java
  back-end/src/main/java/fatec/morpheus/service/NewsService.java
Labels: refactor

#81 [Refactor] Gerenciamento de sinonimos #79
  back-end/src/main/java/fatec/morpheus/DTO/TextDTO.java
  back-end/src/main/java/fatec/morpheus/controller/TextController.java
  back-end/src/main/java/fatec/morpheus/database/ddl.sql
  back-end/src/main/java/fatec/morpheus/entity/Synonymous.java
  back-end/src/main/java/fatec/morpheus/entity/SynonymousId.java
  back-end/src/main/java/fatec/morpheus/entity/Text.java
  back-end/src/main/java/fatec/morpheus/entity/Texto.java
  back-end/src/main/java/fatec/morpheus/repository/SynonymousRepository.java
  back-end/src/main/java/fatec/morpheus/repository/TextRepository.java
  back-end/src/main/java/fatec/morpheus/service/AdaptedTagsService.java
  back-end/src/main/java/fatec/morpheus/service/SynonymousService.java
  back-end/src/main/java/fatec/morpheus/service/TextService.java
  back-end/src/main/java/fatec/morpheus/service/TextoService.java
Labels: refactor

#80 [D] [Web Scrapping] Lógica de Coleta de Dados #40
  .vscode/settings.json
  back-end/pom.xml
  back-end/src/main/java/fatec/morpheus/DTO/MapSourceDTO.java
  back-end/src/main/java/fatec/morpheus/DTO/NewsSourceDTO.java
  back-end/src/main/java/fatec/morpheus/MorpheusApplication.java
  back-end/src/main/java/fatec/morpheus/controller/NewsSourceController.java
  back-end/src/main/java/fatec/morpheus/database/ddl.sql
  back-end/src/main/java/fatec/morpheus/entity/ErrorResponse.java
  back-end/src/main/java/fatec/morpheus/entity/News.java
  back-end/src/main/java/fatec/morpheus/entity/NewsAuthor.java
  back-end/src/main/java/fatec/morpheus/entity/NewsSource.java
  back-end/src/main/java/fatec/morpheus/repository/NewsAuthorRepository.java
  back-end/src/main/java/fatec/morpheus/repository/NewsRepository.java
  back-end/src/main/java/fatec/morpheus/repository/NewsSourceRepository.java
  back-end/src/main/java/fatec/morpheus/service/MapSourceService.java
  back-end/src/main/java/fatec/morpheus/service/NewsService.java
  back-end/src/main/java/fatec/morpheus/service/ScrapingService.java
  config/application.properties
  src/main/resources/application.properties
Labels: enhancement, build

#84 [Integração] Integração do Front com o Back para Portal de Notícias #83
  front-end/html/index.html
  front-end/html/newsFeed.html
  front-end/js/index.js
  front-end/js/newsFeed.js
Labels: enhancement

#95 [Docs] Atualização semanal.
  README.md
  documentation/burndown/BurnDownChartSprint3.png
Labels: documentation
