Repository Morpheus-Fatec/morpheus, pull requests merged in 2024-11, with the labels that each got.

#102 Documentation sprint 3
  back-end/src/main/resources/application.properties
  documentation/burndown/BurnDownChartSprint3.png
Labels: documentation

#105 [Aprimoramento Técnico] Cronograma de coleta de notícias. #97
  back-end/back-end/src/main/resources/application.properties
Labels: refactor

#104 [E - F] [Criação da Interface] Interface de Filtros de Busca #88
  front-end/html/newsFeed.html
  front-end/js/newsFeed.js
Labels: enhancement, build

#103 [E-F][Aprimoramento Técnico] Revisão dos Endpoints #92
  back-end/src/main/java/fatec/morpheus/DTO/TextDTO.java
  back-end/src/main/java/fatec/morpheus/controller/TagController.java
  back-end/src/main/java/fatec/morpheus/controller/TextController.java
  back-end/src/main/java/fatec/morpheus/entity/Synonymous.java
  back-end/src/main/java/fatec/morpheus/entity/SynonymousId.java
  back-end/src/main/java/fatec/morpheus/entity/Tag.java
  back-end/src/main/java/fatec/morpheus/entity/Text.java
  back-end/src/main/java/fatec/morpheus/exception/NotFoundException.java
  back-end/src/main/java/fatec/morpheus/repository/SynonymousRepository.java
  back-end/src/main/java/fatec/morpheus/service/SynonymousService.java
  back-end/src/main/java/fatec/morpheus/service/TextService.java
  front-end/html/index.html
  front-end/js/index.js
Labels: enhancement, build

#108 [Feat] Filtro de autores #106
  back-end/src/main/java/fatec/morpheus/DTO/NewsAuthorDTO.java
  back-end/src/main/java/fatec/morpheus/controller/NewsAuthorController.java
  back-end/src/main/java/fatec/morpheus/exception/GlobalExceptionHandler.java
  back-end/src/main/java/fatec/morpheus/exception/NoAuthorsFoundException.java
  back-end/src/main/java/fatec/morpheus/service/NewsAuthorService.java
Labels: enhancement, build

#110 [E- F][Filtragem de Notícias] Filtro de tags #101
  back-end/src/main/java/fatec/morpheus/DTO/TagDTO.java
  back-end/src/main/java/fatec/morpheus/controller/TagFilterController.java
  back-end/src/main/java/fatec/morpheus/entity/NewsTag.java
  back-end/src/main/java/fatec/morpheus/service/TagService.java
  back-end/src/main/resources/application.properties
Labels: enhancement, build

#100 Revisão do Banco de Dados #93
  back-end/src/main/java/fatec/morpheus/database/ddl.sql
  back-end/src/main/java/fatec/morpheus/entity/Tag.java
  documentation/diagrams/morpheus-bd.jpg
  documentation/diagrams/morpheus-bd.png
Labels: documentation

#98 Integracao da query com endpoint
  back-end/src/main/java/fatec/morpheus/DTO/NewsSearchRequest.java
  back-end/src/main/java/fatec/morpheus/controller/NewsFilterController.java
  back-end/src/main/java/fatec/morpheus/database/ddl.sql
  back-end/src/main/java/fatec/morpheus/service/NewsSpecification.java
Labels: enhancement, build

#109 Revisão da verificação de noticias duplicadas #99
  back-end/src/main/java/fatec/morpheus/entity/News.java
  back-end/src/main/java/fatec/morpheus/service/NewsService.java
  back-end/src/main/java/fatec/morpheus/service/ScrapingService.java
Labels: refactor

#111 Configuração de Timeout do Webscraping#107
  back-end/src/main/java/fatec/morpheus/controller/CronController.java
  back-end/src/main/java/fatec/morpheus/entity/CronProperties.java
  back-end/src/main/java/fatec/morpheus/entity/NewsTag.java
  back-end/src/main/java/fatec/morpheus/service/CronManager.java
  back-end/src/main/resources/application.properties
  front-end/html/index.html
  front-end/js/index.js
Labels: enhancement, build

#113 [Integração] Integração do Front com o Back para Exibição de Noticias #112
  back-end/src/main/java/fatec/morpheus/controller/NewsAuthorController.java
  back-end/src/main/java/fatec/morpheus/controller/NewsFilterController.java
  front-end/js/newsFeed.js
Labels: enhancement, build

#119 [Documentação] Documentação da Sprint 4 #118
  documentation/burndown/BurnDownChartSprint3.png
  documentation/documentation.md
Labels: documentation

#117 [Documentação] Criação de Guia do Usuário #115
  front-end/assets/newsExample.html
  front-end/html/index.html
  front-end/js/index.js
Labels: documentation

#121 Sprint 3
  documentation/burndown/BurnDownChartSprint3.png
Labels: documentation

#127 [G] [Gerenciamento de API] Cadastro de API #124
  back-end/src/main/java/fatec/morpheus/DTO/ApiDTO.java
  back-end/src/main/java/fatec/morpheus/controller/ApiController.java
  back-end/src/main/java/fatec/morpheus/entity/Api.java
  back-end/src/main/java/fatec/morpheus/repository/ApiRepository.java
  back-end/src/main/java/fatec/morpheus/service/ApiService.java
Labels: enhancement, build

#126 [H - I] [Gerenciamento de API] Modelagem do Banco de Dados #123
  back-end/src/main/java/fatec/morpheus/database/ddl.sql
  back-end/src/main/resources/application.properties
Labels: enhancement, build

#142 Atualizado gráfico Burndown até dia 24/11
  documentation/burndown/BurnDownChartSprint4.png
Labels: documentation

#143 [Aprimoramento técnico] Correção do CRUD de APIs #138
  back-end/src/main/java/fatec/morpheus/DTO/ApiDTO.java
  back-end/src/main/java/fatec/morpheus/entity/Api.java
  back-end/src/main/java/fatec/morpheus/repository/ApiRepository.java
  back-end/src/main/java/fatec/morpheus/service/ApiService.java
Labels: refactor

#146 [Aprimoramento técnico] Tratamento de Erros de Exclusão em Cascata #129
  back-end/src/main/java/fatec/morpheus/config/DatabaseConfig.java
  back-end/src/main/resources/application.properties
  front-end/html/index.html
Labels: refactor

#145 [G][Criação da Interface] Interface de Exibição do Conteúdo das APIs #137
  front-end/html/apiFeed.html
  front-end/html/index.html
  front-end/html/newsFeed.html
  front-end/js/apiFeed.js
  front-end/js/newsFeed.js
Labels: enhancement, build
